import Head from "next/head";
import Sidebar from "../composents/Sidebar";

export default function Home() {
  
  return (
    <div>
      <Head>
        <title>Rafik | School</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex ">
        <Sidebar/>
        <div className="p-7">
          <h1 className="text-2xl font-semibold">Home Page</h1>
        </div>
      </div>
    </div>
  );
}
